autosaveMinutes=0
editorBg=#000000
editorColor=#197819
editorFontFamily='Georgia', 'Times New Roman', serif
editorFontSize=18
editorLineHeight=1.8
editorPadding=40px
wordFreqMinLetters=4
lastFile=/Users/daniel/Documents/novela-castro-arinio/mundo/Contexto Histórico/Condes de Castilla.txt
lastProject=/Users/daniel/Documents/novela-castro-arinio/novela-castro-arinio.json
