autosaveMinutes=0
editorBg=#000000
editorColor=#197819
editorFontFamily='Georgia', 'Times New Roman', serif
editorFontSize=18
editorLineHeight=1.8
editorPadding=40px
wordFreqMinLetters=4
lastProject=/Users/daniel/Documents/Novela/El Despertar/project.json
lastFile=/Users/daniel/Documents/Novela/El Despertar/Capítulos/Capítulo 5/1-Calculadores.txt
